# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 017f5a8a0e16d2cd15677fb456710c6c86f493ce02173e292982bc31c6776e56197991ada434d5bad913c1ae24532169a1a0a65817b348335d794ff4a64469e5

test:
  secret_key_base: 08b70ebfd70015d45682349d95e6e8c8419d930f76bd1307d417179363f958d4129b037cbf3bd812c2a739499bb93c7cbe77773aa13c671b0eb89b2906533209

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
